name: Build and Commit Changes

on:
  workflow_dispatch:

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history to ensure 'gh-pages' branch is available

      - name: Set up Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Build project using Webpack/Rollup
        run: |
          npm i
          npm run build

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add -A
          git reset -- node_modules  # Unstage the node_modules changes

          # Check for changes
          if git diff --cached --exit-code; then
            echo "No changes to commit."
          else
            # Loop through changed files
            git diff --cached --name-only | while read -r file; do
              if git diff --cached --name-only -- "$file" | grep -q "^$file\$"; then
                commit_message="Updated $file :inbox_tray:"
              else
                commit_message="Added $file :inbox_tray:"
              fi
              git commit -m "$commit_message" -- "$file"
            done
            git push
          fi
